name: Test

on:
  push:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: integration/go.mod

      - name: Run fuzzing tests
        working-directory: integration
        run: go test -fuzz . -fuzztime 1m
